### PR TITLE
Fix StackLayout fillEqualSpacing distribution with spacing

### PR DESCRIPTION
**Pull request by domasn**
Updates [`StackLayout.distributionConfig`](https://github.com/linkedin/LayoutKit/blob/2df3a704342b3f7e6a6607e52006834f675c2bc5/Sources/Layouts/StackLayout.swift#L221) and calculates the `axisSpacing` taking into account the spaces that were already added during the `measurement` phase. Actual `excessAxisLength` for `.fillEqualSpacing` is increased by `numberOfSpaces * spacing` so it can be redistrubuted.

See issue https://github.com/linkedin/LayoutKit/issues/159

### CODE REVIEW

**Comment by nicksnyder** [comment]
Thanks for the PR! I haven't looked at the issue yet, but this PR will unit need tests before it is mergeable.

**Comment by staguer** [comment]
Thank you for adding unit tests.

I'm curious, why doesn't this PR have the automatic CI verification like the other PRs do?

**Comment by domasn** [comment]
@staguer Great question, I don't really know though. As you can see this pull is from a `fix` branch on my fork, but that shouldn't really matter to CI.

**Comment by nicksnyder** [comment]
It looks like Travis thinks it has detected abuse:
image

I contacted Travis support to see what is going on.

**Comment by nicksnyder** [comment]
@domasn Travis support says the abuse flag has been removed. Please push an empty commit or rebase against master to trigger a new build.

**Pull request merged**
