### PR TITLE
Version bump 5.0.0 to 6.0.0

### PR DESCRIPTION
**Pull request by jingwei-huang1**

### CODE REVIEW

**Comment by nicksnyder** [comment]
Before merging this, you should look through existing open PRs to see if there is anything that can/should be merged

**Comment by nicksnyder** [comment]
I merged https://github.com/linkedin/LayoutKit/pull/155

I think the others can wait

**Comment by nicksnyder** [comment]
https://github.com/linkedin/LayoutKit/pull/150 is probably mergeable. The only comments I had were minor.

**Comment by jingwei-huang1** [comment]
@nicksnyder Thanks for your help! The main purpose for this bump is to support swift 4. I will see if anything else we can bring in.

**Comment by nicksnyder** [comment]
I merged the two PRs that I think were ready. Unsure if they had stuff incompatible with Swift 4 so can watch to see if tests pass. Any time we do a major version bump is a good time to make other changes that may be backward incompatible behavior wise.

**Pull request merged**
